//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankStats
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccount
    {
        public string AccountName { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankAccountSortCode { get; set; }
        public System.Guid AccountID { get; set; }
        public string UserName { get; set; }
    }
}
