//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankStats
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankTransaction
    {
        public System.DateTime Date { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> PaidIn { get; set; }
        public Nullable<decimal> PaidOut { get; set; }
        public Nullable<decimal> Ballance { get; set; }
        public System.Guid TransactionID { get; set; }
        public System.Guid BankAccountID { get; set; }
        public string Target { get; set; }
    }
}
