//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankStats
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionCategory
    {
        public string TransactionTarget { get; set; }
        public string TransactionCategory1 { get; set; }
    }
}
